all: beshenov-weil-etale-complexes.pdf

beshenov-weil-etale-complexes.pdf: beshenov-weil-etale-complexes.tex
	pdflatex beshenov-weil-etale-complexes
	pdflatex beshenov-weil-etale-complexes

.PHONY: clean

clean:
	rm -f *.aux *.bbl *.blg *.log *.out *.toc *~
	rm -f beshenov-weil-etale-complexes.pdf
